# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

language: python 3.6

script: ./test/shanghai_test.py && ./src/shanghai.py demo/*.shanghai
